### ISSUE TITLE
Zaimplementowac asynchronicznosc

### ISSUE THREAD

**Issue by matti2244** [ProjectBookWeb/BookWeb#11]
http://farazdagi.com/blog/2014/rest-long-running-jobs/

More info:
https://www.safaribooksonline.com/library/view/restful-web-services/9780596809140/ch01s10.html
https://www.adayinthelifeof.nl/2011/06/02/asynchronous-operations-in-rest/

**Comment by ProjectBookWeb** [comment]
PUT & DELETE async with EF

http://www.c-sharpcorner.com/UploadFile/dacca2/asynchronous-controller-of-web-api-2-with-entity-framework-6622/
