### ISSUE TITLE
[Cart] PostItemToCart() shows unnecessary items.

### ISSUE THREAD

**Issue by ProjectBookWeb** [ProjectBookWeb/BookWeb#13]
After executing POST method we got json response:

`{
  "CartLineId": 15,
  "CartId": 2,
  "BookId": 2,
  "Count": 1,
  "Cost": 12.95,
  "Book": null,
  "Cart": {
    "CartId": 2,
    "TotalCost": 77.77,
    "CartLines": []
  }
}`

Instead of this show only CartId, BookId, Count and Costs.

**Comment by matti2244** [comment]
Now all POST responses are empty. Only http status (200) is returned.
Fixed in b11229fb70e87c8403663175db01168051ba30a2
