### ISSUE TITLE
Create Register page

### ISSUE THREAD

**Issue by matti2244** [ProjectBookWeb/BookWeb#29]
Backend is done in b71c5c359c14d65e3259bf2ac1f3e9a7b69eea65

Steps for register new user:
1. POST /api/user/register
2. POST /api/cart

http://bookweb-001-site1.btempurl.com/api/user/register
{
    "Username": "User1",
	"Password": "123"
}

If given Username exists, 409 http code will be returned (conflict)

Use always this request, don't change it
http://bookweb-001-site1.btempurl.com/api/cart
{
    "TotalCost": 0
}

**Comment by matti2244** [comment]
post /api/cart/

{
    "TotalCost": 0
}

**Comment by ProjectBookWeb** [comment]
done.
