### ISSUE TITLE
Add log in functionality

### ISSUE THREAD

**Issue by matti2244** [ProjectBookWeb/BookWeb#30]
Example users that already exists in database

Username: Admin
Password: 123

Username: User
Password: 123

**Comment by matti2244** [comment]
Log in User
http://bookweb-001-site1.btempurl.com/api/user/login
Example POST
{
    "Username": "User1",
    "Password": "123"
}

If User **not** exists then 400 (bad request) status code is returned.
If User exists but password is wrong then 400 (bad request) status code is returned.
If both User and password are correct then 200 (Ok) status code is returned

**Comment by ArtysT** [comment]
Done
