### ISSUE TITLE
[Site] Mapa strony

### ISSUE THREAD

**Issue by ProjectBookWeb** [ProjectBookWeb/BookWeb#4]
Wypisz jakos (diagram, drzewo?) z jakich podstron bedzie sie skladala strona, najlepiej z przykladami uzycia (tylko w przypadku gdy bedziemy parsowac jakies dane (na przyklad id) z linka np. www.strona.pl/book/3). Potem do kazdego linku dopisze ci z jakich kodow http bedziesz musial korzystac.

**Comment by ArtysT** [comment]
https://drive.google.com/file/d/0B1oj-o4ZMl3PVDU2Q2pSMDZJYW8/view?usp=sharing
