### ISSUE TITLE
Struktura API

### ISSUE THREAD

**Issue by ProjectBookWeb** [ProjectBookWeb/BookWeb#9]
Dodaje tutaj liste akcji z ktorych mozesz korzystac, dodaje to tutaj poniewaz Help pages mocno daje dupy ostatnio, jak bede miec czas to to zrobie, ale ma to bardzo niski priorytet :P

**KOSZYK:**
Get all carts​
GET strona.pl/api/cart​
​
Get cart by id​
GET strona.pl/api/cart/{id}​
​
Add item to cart​
POST strona.pl/api/cart/{id}/items​

Remove item from cart​
DELETE strona.pl/api/cart/{id}/items/{id2}​

Remove cart​
DELETE strona.pl/api/cart/{id}​

Checkout & calculate​
POST strona.pl/api/cart/{id}/checkout​

**KSIAZKI:**
Get all books
GET strona.pl/api/book​
​
Get book by id​
GET strona.pl/api/cart/{id}​

Edit book
PUT strona.pl/api/book/{id}

Add book
POST strona.pl/api/book

Remove book
DELETE strona.pl/api/book/{id}

**Reszta**
Autorzy i gatunki zostana dodani na samym koncu, struktura bedzie pewnie taka sama jak dla ksiazek.

**Comment by matti2244** [comment]
Lista przeniesiona do README.MD
